# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: LDEO Ocean Transport Group
author: LOT Group
copyright: "2025"
logo: ./_static/otg_logo_blue.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/ocean-transport/ocean-transport.github.io  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
